import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { redis, getCacheKey } from './redis.ts';
import { checkUserSubscription, saveRoadmapToDB } from './db.ts';
import { getCachedRoadmap, cacheRoadmap, generateGeminiRoadmap } from './gemini.ts';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL') || 'https://obzbljyuydzavtjzaikq.supabase.co';
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  let requestBody: any = null;
  let isLocked = false;
  let lockKey = '';

  try {
    if (!SUPABASE_SERVICE_ROLE_KEY) {
      throw new Error('Missing necessary secrets');
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    const authHeader = req.headers.get('Authorization');
    if (!authHeader) throw new Error('No authorization header');
    const token = authHeader.replace('Bearer ', '');
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);
    if (authError || !user) throw new Error('Unauthorized');

    requestBody = await req.json();
    const { skill, level, timeCommitment, learningStyle, goal, timeline } = requestBody;

    if (!skill || !level || !timeCommitment) {
      throw new Error('Missing required fields: skill, level, or timeCommitment');
    }

    const subscription = await checkUserSubscription(supabase, user.id, user.email || '');
    console.log('User subscription:', subscription);

    const timelineWeeks = timeline ? parseInt(timeline.toString()) : 4;

    // Check cache first
    const cachedRoadmap = await getCachedRoadmap(supabase, skill, level, timeCommitment, learningStyle, goal, timelineWeeks.toString());
    if (cachedRoadmap) {
      console.log('✅ Using cached roadmap');
      
      const roadmap = await saveRoadmapToDB(supabase, user.id, {
        skill, level, timeCommitment, learningStyle, goal, timeline: timelineWeeks,
        generated_data: cachedRoadmap
      });

      return new Response(JSON.stringify({
        success: true,
        roadmapId: roadmap.id,
        roadmapData: cachedRoadmap,
        fromCache: true
      }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Cache Stampede Lock Protection
    lockKey = `lock:${getCacheKey(skill, level, timeCommitment, learningStyle, goal, timelineWeeks.toString())}`;
    if (redis) {
      try {
        const acquired = await redis.set(lockKey, "locked", { nx: true, ex: 10 });
        if (!acquired) {
          console.log('🔒 Cache stampede lock active. Waiting for parallel generation...');
          for (let i = 0; i < 12; i++) {
            await new Promise(resolve => setTimeout(resolve, 500));
            const doubleCheck = await getCachedRoadmap(supabase, skill, level, timeCommitment, learningStyle, goal, timelineWeeks.toString());
            if (doubleCheck) {
              console.log('🔓 Cached roadmap generated by parallel request!');
              const roadmap = await saveRoadmapToDB(supabase, user.id, {
                skill, level, timeCommitment, learningStyle, goal, timeline: timelineWeeks,
                generated_data: doubleCheck
              });
              return new Response(JSON.stringify({
                success: true,
                roadmapId: roadmap.id,
                roadmapData: doubleCheck,
                fromCache: true
              }), {
                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
              });
            }
          }
          console.log('🔓 Lock wait timed out. Proceeding with own generation.');
        } else {
          isLocked = true;
        }
      } catch (err) {
        console.error('Lock error, proceeding without stampede lock:', err);
      }
    }

    const prompt = `Create a detailed ${timelineWeeks}-week learning roadmap for "${skill}".\n\nRequirements:\n- Current Level: ${level}\n- Weekly Time Commitment: ${timeCommitment} hours\n- Learning Style: ${learningStyle || 'Mixed'}\n- End Goal: ${goal || 'General mastery'}\n- Timeline: ${timelineWeeks} weeks\n\nReturn ONLY a valid JSON object with this exact structure:\n{\n  "title": "${skill} Mastery Roadmap",\n  "duration": "${timelineWeeks} Weeks",\n  "totalHours": "${timeCommitment}",\n  "motivationalTip": "Stay consistent and practice daily!",\n  "summary": "This roadmap will guide you to master ${skill}",\n  "weeks": [\n    {\n      "week": 1,\n      "title": "Foundation & Setup",\n      "description": "Build fundamentals and setup",\n      "difficulty": "Beginner",\n      "estimatedHours": "${timeCommitment} hours",\n      "goals": ["Learn basics", "Setup environment", "First practice"],\n      "tasks": [\n        {\n          "id": "w1-t1",\n          "title": "Learn ${skill} fundamentals and core concepts",\n          "type": "video",\n          "duration": "2 hours",\n          "resource": "Official documentation"\n        },\n        {\n          "id": "w1-t2", \n          "title": "Setup ${skill} development environment and tools",\n          "type": "practice",\n          "duration": "1 hour",\n          "resource": "Setup guide"\n        }\n      ],\n      "checkpoint": "Complete basic setup and understand core concepts"\n    }\n  ]\n}\n\nSPEED & CONCISENESS REQUIREMENT: To ensure maximum generation speed, keep all text fields (motivational tips, summaries, descriptions, checkpoints, and task titles) brief (maximum of 12 words per text block). Limit every week to exactly 3-4 key tasks to form a proper, comprehensive plan. Make titles descriptive but very concise.\n\nCRITICAL FOR LONG TIMELINES: If the timeline is more than 4 weeks (e.g., 8 or 12 weeks), you MUST keep all titles, descriptions, and goals short and concise, and limit each week to exactly 3 key tasks. This is absolutely necessary to ensure the entire JSON response fits within the token limits and does not get cut off.\n\nFor every task, make the title very specific and searchable for YouTube tutorials. Make titles descriptive and suitable for YouTube search.\n\nMake the roadmap progressive, practical, and tailored to ${level} level. Include ${timelineWeeks} weeks total.`;

    console.log('🚀 Generating roadmap with Gemini...');
    const roadmapData = await generateGeminiRoadmap(supabase, prompt, user.id, subscription.tier);
    
    // Cache the generated roadmap
    await cacheRoadmap(supabase, skill, level, timeCommitment, learningStyle || 'mixed', goal || 'general mastery', timelineWeeks.toString(), roadmapData);

    // Skip YouTube search during initial generation
    console.log('🎥 Skipping YouTube search during initial generation for speed.');

    const roadmap = await saveRoadmapToDB(supabase, user.id, {
      skill, level, timeCommitment, learningStyle, goal, timeline: timelineWeeks,
      generated_data: roadmapData
    });

    return new Response(JSON.stringify({
      success: true,
      roadmapId: roadmap.id,
      roadmapData: roadmapData,
      subscription: subscription
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('💥 Error in generate-roadmap function:', error);
    
    try {
      const db = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
      await db
        .from('roadmap_cache')
        .upsert({
          skill_name: 'debug',
          level: 'error',
          time_commitment: 'log',
          cache_key: 'debug_error_log',
          cached_data: {
            error: error.message || 'Unknown error',
            timestamp: new Date().toISOString(),
            requestBody: requestBody
          }
        }, { onConflict: 'cache_key' });
      console.log('✅ Diagnostic error logged to cache table');
    } catch (dbErr) {
      console.error('💥 Failed to log error to database cache:', dbErr.message);
    }

    return new Response(JSON.stringify({
      error: error.message || 'Failed to generate roadmap'
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } finally {
    if (isLocked && redis) {
      await redis.del(lockKey).catch(err => console.error('Error releasing lock:', err));
    }
  }
});
