// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://phfofzvcnhnwucxyjyts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoZm9menZjbmhud3VjeHlqeXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTEyOTYsImV4cCI6MjA2NTQ2NzI5Nn0.HRP1a2RnmvvDcEMn4Mlkm3If82r6cEMdofaEp6O5vwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);